# This file is for local testing only, see:
# https://devcenter.heroku.com/articles/local-development-with-docker-compose
# Deployment is configured in `heroku.yml` & `app.json`

version: '3'
services:
  web:
    # For platform spec, see https://stackoverflow.com/a/70238851
    platform: linux/amd64
    build: .
    ports:
      - '3000:8000'
    depends_on:
      - db
    environment:
      # Nearly the same config as for postgres service in `.github/workflows/main.yaml`,
      # with exception of hostname. For hostname, see https://docs.docker.com/compose/networking/
      DATABASE_URL: 'postgres://postgres_user:postgres_password@db:5432/postgres_db'
      # These vars are passed in on the call to docker-compose, and then forwarded
      # into the entrypoint script like this.
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      PANGEO_FORGE_DEPLOYMENT: $PANGEO_FORGE_DEPLOYMENT
    entrypoint: /bin/bash ./scripts.deploy/test.sh

  db:
    platform: linux/amd64
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      # Identical config as for postgres service in `.github/workflows/main.yaml`
      POSTGRES_DB: postgres_db
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres_user
