[tool.black]
line-length = 100
target-version = ['py38']
skip-string-normalization = false

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pangeo_forge_orchestrator/_version.py"
write_to_template = "__version__ = '{version}'"
