PANGEO_FORGE_API_KEY: ENC[AES256_GCM,data:oeKJYO7KubW5W8/TwDJjO37BKCqGXMPk0U4eiMUPKAc=,iv:oQfxst9lGTpO1r9Mu3DXenpAl1u1bsFKIl6RGZoEw68=,tag:Q8KKgD89tdnu/3RpBm/pZQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256317687910:key/d8b153c3-20a9-4364-a553-94405d4c1027
          created_at: "2022-11-29T19:22:30Z"
          enc: AQICAHgpH4G+b2ULBcvMucaHVvQi3QdX1B0xlVvF3iFfhxUVOwF6OnsihlCgp5etPSQBMnMFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQSHESxZpJXV+zN7bAgEQgDu7gL6P9WxssCuQ0DKZUHsP1ayO2fMNst9Uo/IQfVvCChnUSnJNvHus4g88yDFYCxaOBcpf4v+KiR7s4g==
          aws_profile: ""
        - arn: arn:aws:kms:us-west-1:256317687910:key/0f31de65-bcc9-4fef-b9f5-67ce086f532e
          created_at: "2022-11-29T19:22:30Z"
          enc: AQICAHiYQfpCkhiXnfU8apZYPITKv6caFhMAr7Hx04ufaTWvvgELeVQLtnCllfmMSoJVfcBMAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMS95BaL6KXzWgbpzoAgEQgDub/bI7BS01Cs4sHA1W2hwmYKlzESZykJcDT4vz/mLQ6IldfdnTjBLEIOGmqr5DaH2QW4RgRr27pgyiXg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-29T19:22:31Z"
    mac: ENC[AES256_GCM,data:eJrBcebNxOqyMUi/HcWfEKxBTL0BqVO3bZN+gyN8BYpzRhr0zFY+gBlEM+88g5wX99PeY//wNFNn27Ac4ls90abMAg21q6en9q64r5QAyO0NsiNFxhqM5SuHh5WPSN0Onyldw5aOKk1ggzAOmngdzesD+RnaVsNG43KpxXlGELs=,iv:J/6fDmGZVG2W8vbVPd2GhRPYIy4uZjdvN+kwj+EA9hQ=,tag:cMGz8+f6gAYAdP2EXjQePQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
