"""remove api keys

Revision ID: 0499cef6b57a
Revises: 70bcddc9fffa
Create Date: 2022-09-25 14:25:18.790980

"""
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0499cef6b57a"
down_revision = "70bcddc9fffa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apikey")
    op.alter_column("reciperun", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reciperun", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "apikey",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("encrypted_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("encrypted_key", name="apikey_pkey"),
    )
    # ### end Alembic commands ###
