"""Add bakery table

Revision ID: 22828222f2fe
Revises: 81c7d27bde71
Create Date: 2022-01-19 14:35:15.140807

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "22828222f2fe"
down_revision = "81c7d27bde71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bakery",
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bakery_description"), "bakery", ["description"], unique=False)
    op.create_index(op.f("ix_bakery_id"), "bakery", ["id"], unique=False)
    op.create_index(op.f("ix_bakery_name"), "bakery", ["name"], unique=False)
    op.create_index(op.f("ix_bakery_region"), "bakery", ["region"], unique=False)
    op.create_index(op.f("ix_reciperun_bakery_id"), "reciperun", ["bakery_id"], unique=False)
    op.create_index(op.f("ix_reciperun_completed_at"), "reciperun", ["completed_at"], unique=False)
    op.create_index(op.f("ix_reciperun_conclusion"), "reciperun", ["conclusion"], unique=False)
    op.create_index(op.f("ix_reciperun_feedstock_id"), "reciperun", ["feedstock_id"], unique=False)
    op.create_index(op.f("ix_reciperun_head_sha"), "reciperun", ["head_sha"], unique=False)
    op.create_index(op.f("ix_reciperun_id"), "reciperun", ["id"], unique=False)
    op.create_index(op.f("ix_reciperun_message"), "reciperun", ["message"], unique=False)
    op.create_index(op.f("ix_reciperun_recipe_id"), "reciperun", ["recipe_id"], unique=False)
    op.create_index(op.f("ix_reciperun_started_at"), "reciperun", ["started_at"], unique=False)
    op.create_index(op.f("ix_reciperun_status"), "reciperun", ["status"], unique=False)
    op.create_index(op.f("ix_reciperun_version"), "reciperun", ["version"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reciperun_version"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_status"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_started_at"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_recipe_id"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_message"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_id"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_head_sha"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_feedstock_id"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_conclusion"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_completed_at"), table_name="reciperun")
    op.drop_index(op.f("ix_reciperun_bakery_id"), table_name="reciperun")
    op.drop_index(op.f("ix_bakery_region"), table_name="bakery")
    op.drop_index(op.f("ix_bakery_name"), table_name="bakery")
    op.drop_index(op.f("ix_bakery_id"), table_name="bakery")
    op.drop_index(op.f("ix_bakery_description"), table_name="bakery")
    op.drop_table("bakery")
    # ### end Alembic commands ###
