"""Initial Migration

Revision ID: 788675cfe27c
Revises:
Create Date: 2022-01-16 12:58:35.141047

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "788675cfe27c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reciperun",
        sa.Column("recipe_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_date", sa.DateTime(), nullable=False),
        sa.Column("bakery_id", sa.Integer(), nullable=False),
        sa.Column("feedstock_id", sa.Integer(), nullable=False),
        sa.Column("commit", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reciperun")
    # ### end Alembic commands ###
