PANGEO_FORGE_API_KEY: ENC[AES256_GCM,data:eP+wbKWeUsu954mhgGLSSs4l3IUqPOTDEhjmoVED0u8=,iv:y2PuUKsvixntMsS58vw9RJCHah6miOb3Fv21NDL9lW0=,tag:J5dYkN8Xamcv99qlPYJq6w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256317687910:key/d8b153c3-20a9-4364-a553-94405d4c1027
          created_at: "2022-12-28T18:14:20Z"
          enc: AQICAHgpH4G+b2ULBcvMucaHVvQi3QdX1B0xlVvF3iFfhxUVOwGkLuiVwMmLDzW0JaHB5z1SAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaydXkIa9hctEi6k5AgEQgDs4AQ2uIr8631rQwv/nG0kkFVInB9JRLrcVeHx3KpyQfR+ozB9zPR2BE3IN1nwlg3ptuKUz4kyHopfAZQ==
          aws_profile: ""
        - arn: arn:aws:kms:us-west-1:256317687910:key/0f31de65-bcc9-4fef-b9f5-67ce086f532e
          created_at: "2022-12-28T18:14:20Z"
          enc: AQICAHiYQfpCkhiXnfU8apZYPITKv6caFhMAr7Hx04ufaTWvvgHgwssWgO6bBArCFukym5A0AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMAwyNsqhVJtfoHGNaAgEQgDv61MxKfStABvQCAlsEKUEulMXFaFdEcEzpCZmoTbfdyoR1cH9ETeCAbC6Bpg54W2Y16Nislh3JKlQQAg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-28T18:14:21Z"
    mac: ENC[AES256_GCM,data:d4dYSN2BMCxFRYze7lOUgXyOe47bdXTpWRjwB+uim5lL9Dcvfcs3wht3rWlYIOzmU6104L6vMwMnfr/c/g+cvROPME3yqAJRGQezemeDSgGC8QLuvUnbeG4lHwXQMy0+YX7M3HnjbnUxeiENzVT3jyMZdBnBi5D0dc6Ip9/VehQ=,iv:ZUpHK1ZPvAfAWqriWHiNyG/Hhek0YvKZ6uxUNQADYjg=,tag:sz9B79/52Z9a28kX75uf0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
