PANGEO_FORGE_API_KEY: ENC[AES256_GCM,data:0ONRKp7bb3vOVPoggqxbaG+0gm6YpKnjcAdUv1OuUp0=,iv:COQykPfwlN7+fGAfsY3btoQEvWx0SZxvZ2topJ2ihnI=,tag:N7LsU7KdhVfs7CD0qLJBPg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256317687910:key/d8b153c3-20a9-4364-a553-94405d4c1027
          created_at: "2022-12-28T19:01:11Z"
          enc: AQICAHgpH4G+b2ULBcvMucaHVvQi3QdX1B0xlVvF3iFfhxUVOwGm2VyJJwTErh4yBOywSb33AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj87fRmSuJ6BDHw41AgEQgDtKTC6c3zQxGezu93CqhZwTs0G19eCPq3WUZe8ZdUWbyDCsqraS9KDH8pYiFXs0t/XWMGnfugmmPQkFvA==
          aws_profile: ""
        - arn: arn:aws:kms:us-west-1:256317687910:key/0f31de65-bcc9-4fef-b9f5-67ce086f532e
          created_at: "2022-12-28T19:01:11Z"
          enc: AQICAHiYQfpCkhiXnfU8apZYPITKv6caFhMAr7Hx04ufaTWvvgGoUOaaepWZplG/HQ/nyZv8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMuQRY7XfLcNDkftTeAgEQgDtag49XvjtGB3zzkXHfb0c3owWMV7bn2frm/xe7ixjHJO/0q7HwgotTq7YIDC9dmTbkWnpqTEGzIYvANA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-28T19:01:11Z"
    mac: ENC[AES256_GCM,data:T7MiebdA+FJPMcH83KZN8SC1HYLhq+IzZcv0dXuTRMvWcnL3km7P6m4rw4ABmBGoaEZnjct5LPzePHMWXo4IBvlXnXoqVLSRaVeoTItMJdMBVQghjw2InO7fIZW7EvVYC0gL2nkqgArdWg7OsPPdyE9Y7EDXJBvepE2mIgMl+b4=,iv:7HDYwv5p47+WeyAiGi7FAw77hv4j7XZ1lqTB1IlcFYQ=,tag:olX8EN8DrRHNSjEeN9U+rg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
