PANGEO_FORGE_API_KEY: ENC[AES256_GCM,data:4d+8dI+vhh8qwlEWKanYBh/+a0x8+P1DNDLnJXEm3RA=,iv:HG4TBEZzU2ZuTZwUc/4i34HKdfLH2B2e6r9nSeX/Jcg=,tag:1D1sp0e7ulsCO7UAJ15VdA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256317687910:key/d8b153c3-20a9-4364-a553-94405d4c1027
          created_at: "2022-12-28T19:00:52Z"
          enc: AQICAHgpH4G+b2ULBcvMucaHVvQi3QdX1B0xlVvF3iFfhxUVOwEyK93ITnurJKux86yuPqhYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2OjetCaAcaTAnGZyAgEQgDuU2+WVPChq0WjWF5USvbTvIid4MHrna6XOG4Kh5s3Xbl2T3qSgE52qvGerIjE5pb7I7t6/FOJJaPbcIw==
          aws_profile: ""
        - arn: arn:aws:kms:us-west-1:256317687910:key/0f31de65-bcc9-4fef-b9f5-67ce086f532e
          created_at: "2022-12-28T19:00:52Z"
          enc: AQICAHiYQfpCkhiXnfU8apZYPITKv6caFhMAr7Hx04ufaTWvvgH1dv3zi4nwWtzm5k71SXI6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzXiiUCrVpGcdTdNCAgEQgDsbYgAhYwZbyNFHs7yetwYoIjI4h8TtDnM9hEFslWUiHjUJAEqrqQmM647qvkembbfJ1vbssVD8wLL5rw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-28T19:00:53Z"
    mac: ENC[AES256_GCM,data:ZeIq3ns43YQHoSqeXkaM7qREZ5jz21YCFxyALPclDuii6eqSsOAl4QxLu1FjwMWXmyk2fDc2ddrCqan9RwaVr7g5oUeUS3zKyqaR2F5DCHCFncA8FEbQzECtXGxrbSUpfohy9aqe+CqX5jL+g7xCqeszh7zBNWSxQVXFI40EfD4=,iv:Yg+GKnyRgSxFZ+vn/Ze/EjRYwps8zgytVYb5pTZzl+g=,tag:AoqiRTTIkBdeUCVoX/xT0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
