name: Dataflow Integration Test

on:
  push:
    branches: main
  repository_dispatch:
    types: [run-dataflow-integration-test-command]
  workflow_dispatch:

env:
  PYTEST_ADDOPTS: '--color=yes'
  python-version: '3.9'

jobs:
  dataflow-integration-test:
    name:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - payload: ''
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'repository_dispatch' }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'repository_dispatch' }}
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      # start a check
      - name: ✅ Register Check Started
        id: start-check
        uses: LouisBrunner/checks-action@v1.5.0
        if: ${{ github.event_name == 'repository_dispatch' }}
        with:
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          # can't use default token
          # https://github.community/t/create-a-check-run-details-url-is-not-being-set/166002/4?u=bkwhite
          # https://github.com/LouisBrunner/checks-action/issues/18#issuecomment-970312052
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Payload ${{ matrix.payload }}
          status: in_progress
          # this seems to be broken
          details_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

      # TODO: build the docker stack and send a payload via curl here

      # finish the check
      # this won't work if we are not inside a repository_dispatch event,
      # but I don't see how to combine multiple if statements
      - uses: LouisBrunner/checks-action@v1.5.0
        if: ${{ always() && steps.start-check.outputs.check_id }}
        with:
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ steps.start-check.outputs.check_id }}
          status: completed
          conclusion: ${{ job.status }}
