name: CI

on:
  push:
    branches:
      - main
      - prod
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - prod
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  test:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pfo
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - name: install pangeo-forge-orchestrator plus deps
        shell: bash -l {0}
        run: |
          pip install -e '.[dev]'
      - name: print conda env
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest tests_ -v --cov=pangeo_forge_orchestrator \
            --cov-config .coveragerc \
            --cov-report term-missing \
            --cov-report xml \
            --durations=10 --durations-min=1.0
      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
