name: Push Dataflow Container Image to GCR

on:
  push:
    branches:
      - main
      - prod
    paths:
      - 'dataflow-container-image.txt'
  pull_request:
    branches:
      - main
      - prod
    paths:
      - 'dataflow-container-image.txt'

jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: pangeo-forge-4967
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CONTAINER_REGISTRY_CREDS }}'
      - name: 'Setup gcloud'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: push image to gcr
        run: >
          export IMAGE_SRC=$(cat dataflow-container-image.txt)
          && docker pull $IMAGE_SRC
          && export IMAGE_DST=gcr.io/${{ env.GCP_PROJECT }}/$IMAGE_SRC
          && docker tag $IMAGE_SRC $IMAGE_DST
          && gcloud docker push $IMAGE_DST
