name: Push Dataflow Container Image to GCR

on:
  push:
    branches:
      - main
      - prod
    paths:
      - 'dataflow-container-image.txt'
  pull_request:
    branches:
      - main
      - prod
    paths:
      - 'dataflow-container-image.txt'

jobs:
  push-image:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: pangeo-forge-4967
    steps:
      - uses: actions/checkout@v2
      - name: push image to gcr
        run: >
          echo ${{ secrets.GOOGLE_CONTAINER_REGISTRY_CREDS }} \
          | docker login -u _json_key --password-stdin https://gcr.io
          && export IMAGE_SRC=$(cat dataflow-container-image.txt)
          && docker pull $IMAGE_SRC
          && export IMAGE_DST=gcr.io/${{ env.GCP_PROJECT }}/$IMAGE_SRC
          && docker tag $IMAGE_SRC $IMAGE_DST
          && docker push $IMAGE_DST
