name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.SLASH_COMMAND_TOKEN }}
          commands: run-dataflow-integration-test
          # users with write permission to this repo can trigger this test
          # this test uses real dataflow resources so it seems like it makes
          # sense to limit who can dispatch it
          permission: write
          issue-type: pull-request
