# Compare: https://github.com/peter-evans/docker-compose-actions-workflow

name: Tests
on:
  push:
    branches:
      - main
      - prod
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
      - prod
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build
      - name: Test
        run: >
          docker-compose run
          -v ${PWD}/tests:/tests
          --entrypoint="/bin/sh -c 'sleep 1
          && python3.9 -m alembic upgrade head
          && apt-get install -y git
          && pip install \".[dev]\"
          && pytest tests -vx'"
          web
