name: Test Dataflow Integration

on:
  deployment_status:
  # TODO: add on 'schedule' against staging deployment?
  pull_request:
    branches: ['main']
    types: [labeled]

jobs:
  test:
    # run when:
    #  - a PR is labeled 'test-dataflow'
    #    (assuming it is also labeled 'build-review-app'
    #    *and* the deployment for the head sha is a success)
    #  - heroku marks a deployment with 'state' == 'success'
    #    (assuming PR also has 'test-dataflow' label)
    runs-on: ubuntu-latest
    steps:
      # conditional step if triggering event is a pull_request
      - name: Maybe set REVIEW_APP_URL and DEPLOYMENT_STATE from pull_request
        if: |
          github.event_name == 'pull_request'
          && github.event.label.name == 'test-dataflow'
          && contains( github.event.pull_request.labels.*.name, 'build-review-app')
        # if we get here, this is a pull request, so we need to know the statuses url
        # for the deployment associated with the head sha. we use the **base** repo
        # deployments url, and look for deployments associated with pr's head sha.
        # (the head repo deployments url would cause errors, if the pr is from a fork.)
        run: |
          export DEPLOYMENTS_URL=\
          ${{ github.event.pull_request.base.repo.deployments_url }}\
          \?environment\=pforge-pr-${{ github.event.pull_request.number }}\
          \&sha\=${{ github.event.pull_request.head.sha }}
          curl -s $DEPLOYMENTS_URL \
          | python3 -c "
          import sys, json; print(json.load(sys.stdin)[0]['statuses_url'])" \
          | xargs -I{} curl -s {} \
          | python3 -c "
          import sys, json;
          d = json.load(sys.stdin)[-1];
          print('TEST_DATAFLOW=True');
          print('DEPLOYMENT_STATE=' + d['state']);
          print('REVIEW_APP_URL=' + d['environment_url']);" \
          >> $GITHUB_ENV

      # conditional step if triggering event is deployment_status
      - name: Maybe set REVIEW_APP_URL and DEPLOYMENT_STATE from deployment_status
        if: |
          github.event_name == 'deployment_status'
        # if we're here, we know this is a deployment_status event, but we don't know whether or not
        # the PR has the 'test-dataflow' label. (it's possible the PR *only* has the 'build-review-app'
        # label, but not the 'test-dataflow' label, in which case we do not want to deploy a dataflow job.
        # so before we do anything else, we need to make sure this PR is labeled 'test-dataflow'.
        # note that the github deployment "environments" for our review apps are named according to the
        # convention "pforge-pr-${NUMBER}". so our most direct path to get the PR number from the deployment
        # status event is to parse the PR number out of this string.
        run: |
          export ENVIRONMENT=${{ github.event.deployment_status.environment }} \
          && python3 -c "
          import os; print(os.environ['ENVIRONMENT'].split('-')[-1])" \
          | xargs -I{} curl -s ${{ github.event.deployment_status.repository_url }}/pulls/{} \
          | python3 -c "
          import json, sys;
          labels = json.load(sys.stdin)['labels'];
          print('TEST_DATAFLOW=' + (True if any([l['name'] == 'test-dataflow' for l in labels]) else False));
          print('REVIEW_APP_URL=' + '${{ github.event.deployment_status.environment_url }}');
          print('DEPLOYMENT_STATE=' + '${{ github.event.deployment_status.state }}');" \
          >> $GITHUB_ENV

      - name: Is app up?
        # NOTE: Heroku updates deployment as 'success' when build succeedes, not when release succeedes.
        # So there is actually still a latency between setting this status, and when the review app is
        # ready to receive payloads. Hmm...
        if: ${{ env.DEPLOYMENT_STATE == 'success' }}
        #   - check to see if app has been released (or if it's just been built)
        #   - if only built, then sleep until it's been released
        run: |
          curl -s env.REVIEW_APP_URL \
          | python3 -c "
          import sys;
          IS_UP = True if sys.stdin.read() == '{\"status\":\"ok\"}' else False; print(f'{IS_UP=}')" \
          >> $GITHUB_ENV

      - name: Run test
        if: |
          env.DEPLOYMENT_STATE == 'success'
          && env.IS_UP == 'True'
          && env.TEST_DATAFLOW == 'True'
        # TODO:
        #   - programatically make a /run comment on an existing PR in pforgetest
        #   - check to ensure a dataflow job was submitted within a plausible timeframe
        #   - wait for the job to complete (5-6 mins)
        #   - check to make sure the job was successful
        run: |
          echo foo
