GitHubApp:
  id: ENC[AES256_GCM,data:+FaQIabQEQ==,iv:fl3KGixvrP33kPuvZpjszovis43wQGEUD09ysUewvkg=,tag:G2Ox7Iv7PCOG/XnWOM4YQQ==,type:int]
  installation_id: ENC[AES256_GCM,data:2nt1ApYZ3QOKzA==,iv:F86kC8f5ZcaR3fwUR/mMNRp7wiTE3/4nKnj3x/1e9Ro=,tag:6wfdeas5Y9KoPPUEvOdjVw==,type:int]
  webhook_url: ENC[AES256_GCM,data:WDqj,iv:od4rVRR+6llgpXXq/YyEiKscqxg8lJOXy+BvLjbQSPQ=,tag:mQ3+xw3v3RluawuxRDjA5Q==,type:str]
  webhook_secret: ENC[AES256_GCM,data:YIa5,iv:kfEt/7wt32rpO0z5R7eJsOR1Zw1oUrIkxE6dI96XGp0=,tag:bTXuMJDSmhKkNj/UHbN6gg==,type:str]
  private_key: ENC[AES256_GCM,data:IPee,iv:yuV3RnJWjoIgTZtYBCbU2WHctBydArOEKrQ7ptac6FU=,tag:UyndNlNgjmkDk6veAUxj0A==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/pangeo-forge-4967/locations/us-central1/keyRings/sops/cryptoKeys/sops-key
      created_at: '2022-08-17T03:34:16Z'
      enc: CiQATVT6br7zXz6Ybga/SBe2enjlb8SyZ1CnrMRjmkt0ienhIr8SSQBuXI8wpc73ssxOiWRGvAv8+Au4JsloXJ5p3fawaJhvQEaXgulXPsoH/MZLRhgdLl/GKJbZrILs5BjjVOgw1F0dVqXh6KBOPM8=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-08-17T03:34:17Z'
  mac: ENC[AES256_GCM,data:OzQdWwMiQRziGSyLVoKhmkSk60Gji8Tlu0t/j+MGClQVpzQAuWxftDvPyfo/NdyydbWkbC9vbBarU26l5QwJ7DtOOiSvLHLpc/SqJfPpP8UCcH+dOxEoTjbZlcQ/+HDMHQ/IuHijNOtwDm5Mg/uEJiXU6t3ukNOQd8Z2Q49moD8=,iv:dJ9+H1AXyMxhmJ6V3sshADQcXiwH2T+lXiq3M6XwdIc=,tag:mU362d6DtDN98K3glFi9YQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
