GitHubApp:
  installation_id: ENC[AES256_GCM,data:auJs,iv:57WbAQHIvM4k9ImBLBWD351+xbi/8gpJHdiQiX53GbM=,tag:elNQJ4aL2B/oWA4E/lUmdw==,type:int]
  webhook_url: ENC[AES256_GCM,data:2dKU,iv:Xdeob34LLkb1mZCjSG0xU6i4kih1+WZ1FyjvxQuJG0E=,tag:jWdRNTN1+UOpO/6eyTYdmw==,type:str]
  private_key: ENC[AES256_GCM,data:VIOI,iv:9+vbhbajY+lRv6kBmasRJRlZUyTesJ/nAE1cVKWjNtg=,tag:8dG0LpBzEXg3fpH3QkyZpA==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/pangeo-forge-4967/locations/us-central1/keyRings/sops/cryptoKeys/sops-key
      created_at: '2022-08-16T19:11:26Z'
      enc: CiQATVT6bpyOnQSmPdGWm6l+17y2yu2I0Ji28VPfFTrjBdWvg4USSQBuXI8wNZLyo29lJy8mU89bh6x5hEQEkkxQ6mM0tJ+DJ+UNdDUkJR4WjDFSrLe9UL9VFQgrYB18fCiMgTs+7JcXoFwa8N7FK6s=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-08-16T19:11:27Z'
  mac: ENC[AES256_GCM,data:1M52A8GQxAVESt/a/Bs1bfZc7ry6FIktF9cjah8YDdhM/GUV4/6xZmdklmYb8R/2N0s5Gjk/rU7Lj1+oJdTvBWvO4blPnnlbqPwtSyQoCERF9Z7YV++0CuZOWIxdwppxpm33fiPp1dBa/b4VmvCIUTGNkWhvhfAhuI4+Ccb6Tbc=,iv:nB5ToqWsT9PcI7RBrM7X/pp2hYO5YE6asM62ePi01ys=,tag:B7uJHWTp1yVaJu3RgoX1kA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
